build: false

environment:
  matrix:
    - PY27:
      PYTHON: "C:\\Python27-x64"
      RUBY_VERSION: "22"
    - PY35:
      PYTHON: "C:\\Python35-x64"
      RUBY_VERSION: "22"

init:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - SET PATH=C:\Ruby22\bin;%PATH%
  - ruby -v
  - gem -v
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  - psql --version

install:
  - gem install mime-types -v 2.6.2  # Required to install taskjuggler
  - gem install taskjuggler
  - "%PYTHON%/Scripts/pip.exe install sqlalchemy psycopg2-binary jinja2 alembic mako markupsafe python-editor coverage pytz tzlocal pytest pytest-xdist pytest-cov"

services:
  - postgresql95

before_test:
    - psql -c "CREATE USER stalker_admin WITH PASSWORD 'stalker' SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;" -U postgres
    - psql -c "CREATE DATABASE stalker_test WITH OWNER = stalker_admin ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;" -U postgres

test_script:
  - py.test -n auto --cov-report term --cov=stalker tests
